default:
	gcc -Wall devcreate.c -o devcreate
	gcc -Wall devtest.c -o devtest
#	gcc -Wall devdelete.c -o devdelete
#	gcc -Wall devdisplay.c -o devdisplay

clean:
	rm -f devcreate devdelete devdisplay devtest
